"""Update models

Revision ID: 2c28e7a450c3
Revises: 9f13cb4e02c8
Create Date: 2024-05-31 15:20:15.704397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c28e7a450c3'
down_revision = '9f13cb4e02c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
